# Generated by Django 4.1.7 on 2023-03-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('current_position', models.TextField()),
                ('location', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
