# Generated by Django 4.1.7 on 2023-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='about',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='victim',
            name='current_position',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='victim',
            name='location',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='victim',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
