# Generated by Django 4.1.7 on 2023-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_victim_companies_victim_durations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=100)),
            ],
        ),
    ]
