# Generated by Django 4.1.7 on 2023-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_victim_template_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='template_number',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
